# -*- coding: utf-8 -*-
"""Projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eOmIlSy-lIj_ZR1e6B-UoojDmVT-pH5N
"""


!pip install ydata-profiling
import pandas as pd
import numpy as np

from ydata_profiling import ProfileReport

from google.colab import drive

drive.mount('/content/drive')
arquivo = '/content/drive/MyDrive/data/relatorio.csv'
with open(arquivo,'r', encoding='UTF-8') as f:
  linhas = f.readlines()
  for i in range (0,5):
    print(f"linha:{i+1}: {linhas[i]}")

df = pd.read_csv(arquivo,low_memory=False , sep=';', encoding='UTF-8')

df.head(5)

df.info()

colunas= df.columns.tolist()
print("colunas")
for coluna in colunas:
  print(coluna)

def convert_number(numero):
  if isinstance(numero, str): # Check if the number is a string
    numero = numero.replace('.','').replace(',','.')
    return float(numero)
  else:
    return numero # Return the number as is if it's not a string

coluna = 'Quantidade Transportada'
df[coluna] = df[coluna].apply(convert_number)

data = ProfileReport(df)
display(data)

coluna = 'Estado'
Estado = df[coluna].value_counts().sort_index()
print(f"Total de operações por {coluna}:")
print(Estado)

transp = 'Tipo de Transporte'
Transporte = df[transp].value_counts().sort_index()
print(Transporte)

unid = 'Unidade de Medida'
unidade = df[unid].value_counts().sort_values(ascending=False)
print(f"Tipos de {unid}:")
pd.set_option('display.max_rows',None)
print(unidade)

filtro_1 = 'kilogramas'
filtro_2 = 'SAO PAULO'
filtro_3 = 2023
segmento_df = df[(df['Unidade de Medida'] == filtro_1) & (df['Estado'] == filtro_2) & (df['Ano'] == filtro_3)]
segmento_df.head(3)

display(ProfileReport(segmento_df))

segmento_df.to_csv('SP.csv', index=True, encoding='UTF-8')

coluna = 'UF - origem'
UFOrigem = df[coluna].value_counts().sort_index()
print(f"Total de partidas de {coluna}:")
print(UFOrigem)

df.loc[df['Unidade de Medida'] == 'Toneladas', 'Quantidade Transportada'] = df.loc[df['Unidade de Medida'] == 'Toneladas', 'Quantidade Transportada'] * 1000

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive